{
 "title": "General API",
 "description": "API metrics for all services.",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total API Requests By Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    { "expr": "requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Total Failed API Calls By Service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    { "expr": "failed_requests_total", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "API Request Duration Histogram",
   "type": "histogram",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(rate(api_response_time_seconds_bucket[5m])) by (le)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}