apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cinepik-ingress
  annotations:
    # Removes routing path
    nginx.ingress.kubernetes.io/use-regex: 'true'
    nginx.ingress.kubernetes.io/rewrite-target: /$2
    # nginx.org/server-snippets: |
    #   location / {
    #     proxy_set_header X-Forwarded-For $host;
    #     proxy_set_header X-Forwarded-Proto $scheme;
    #   }
spec:
  ingressClassName: webapprouting.kubernetes.azure.com
  rules:
    # - host: cinepik.fun
    - http:
        paths:
          - path: /catalog(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: cinepik-catalog
                port:
                  number: 3001
          - path: /auth(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: cinepik-auth
                port:
                  number: 3000
          - path: /watchlist(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: cinepik-watchlist
                port:
                  number: 3002
          - path: /recommendations(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: cinepik-recommendation-engine
                port:
                  number: 3003
          - path: /kibana(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: kibana-service
                port:
                  number: 5601
